sdk/tests/tutorials/ibor/test_cut_labels.py
sdk/tests/utilities/test_data_utilities.py

Dev 4625 : add cut labels sdk examples

---

sdk/tests/tutorials/marketdata/test_instruments.py

DEV-4522 Update for API changes

---

sdk/tests/tutorials/marketdata/test_instruments.py

DEV-4494 API changes for UpsertInstrumentsProperties

---

sdk/lusid/utilities/__init__.py
sdk/lusid/utilities/api_client_factory.py
sdk/tests/utilities/__init__.py
sdk/tests/utilities/test_api_client_factory.py
sdk/tests/utilities/test_token_refresh.py
sdk/tests/utilities/token_utilities.py

Add an API factory to initialise API implementations with a token

DEV-5286 Add api factory

---

sdk/tests/tutorials/ibor/test_portfolios.py
sdk/tests/tutorials/ibor/test_properties.py
sdk/tests/tutorials/ibor/test_transactions.py
sdk/tests/tutorials/marketdata/test_instruments.py
sdk/tests/utilities/instrument_loader.py
sdk/tests/utilities/test_data_utilities.py

TR-282: Fix API functions

---

sdk/lusid/utilities/api_client_builder.py
sdk/lusid/utilities/api_client_factory.py
sdk/lusid/utilities/api_configuration_loader.py
sdk/tests/utilities/test_api_client_factory.py
sdk/tests/utilities/test_api_configuration_loader.py

Improve ApiFactory initialisation

DEV-5618 Improve ApiFactory initialisation

---

sdk/tests/tutorials/ibor/test_valuation.py

DEV-5134 Migrate to QuotesApi

---

sdk/lusid/utilities/api_client_factory.py
sdk/tests/utilities/test_api_client_factory.py

- [] Read the [contributing guidelines](https://github.com/finbourne/lusid-sdk-python-preview/blob/master/CONTRIBUTING.md)
This PR checks for a FBN_LUSID_API_URL environmental variable when attempting to build the API factory. 
Note - I am getting a 404 error when trying to read the contributing guidelines in the checklist above.

adding env variable for API URL

---

sdk/lusid/utilities/api_client_factory.py
sdk/tests/utilities/test_api_client_factory.py

adding env var for api url

---

sdk/lusid/utilities/api_client_factory.py
sdk/tests/utilities/test_api_client_factory.py

adding condition for None token

---

sdk/lusid/utilities/api_client_factory.py
sdk/tests/utilities/test_api_client_factory.py

Feature/dev 6098.none str condition

---

sdk/lusid/utilities/api_client_factory.py

updating api_client

---

sdk/lusid/utilities/api_client_builder.py
sdk/tests/utilities/test_api_client_builder.py

Pass values to ApiClientBuilder

DEV-6443 Pass values to ApiClientBuilder

---

sdk/tests/tutorials/marketdata/test_quotes.py

Fix incorrect test assertion that was giving false positives

Fix incorrect test assertion

---

sdk/setup.py

- [ x] Read the [contributing guidelines](https://github.com/finbourne/lusid-sdk-python-preview/blob/master/CONTRIBUTING.md)
- [x ] Tests pass
- [x ] Raised the PR against the `develop` branch

DEV-7126 Update REQUIRES in Setup.py to match requirements.txt

---

sdk/lusid/tcp/__init__.py
sdk/lusid/tcp/tcp_keep_alive_probes.py
sdk/lusid/utilities/__init__.py
sdk/lusid/utilities/api_client_builder.py
sdk/lusid/utilities/api_client_factory.py
sdk/lusid/utilities/api_configuration.py
sdk/lusid/utilities/api_configuration_loader.py
sdk/lusid/utilities/config_keys.json
sdk/lusid/utilities/lusid_retry.py
sdk/lusid/utilities/proxy_config.py
sdk/lusid/utilities/refreshing_token.py

DEV-7599 Restore deleted files

---

sdk/lusid/tcp/tcp_keep_alive_probes.py

- [x ] Read the [contributing guidelines](../docs/CONTRIBUTING.md)
- [x ] Tests pass
- [ x] Raised the PR against the `develop` branch

DEV-7646 Prevent Linux socket options from being set temporarily

---

sdk/tests/tutorials/ibor/test_bitemporal.py
sdk/tests/tutorials/ibor/test_cut_labels.py
sdk/tests/tutorials/ibor/test_holdings.py
sdk/tests/tutorials/ibor/test_portfolios.py
sdk/tests/tutorials/ibor/test_properties.py
sdk/tests/tutorials/ibor/test_reconciliation.py
sdk/tests/tutorials/ibor/test_transactions.py
sdk/tests/tutorials/ibor/test_valuation.py
sdk/tests/tutorials/marketdata/test_instruments.py
sdk/tests/tutorials/marketdata/test_quotes.py
sdk/tests/utilities/instrument_loader.py
sdk/tests/utilities/test_data_utilities.py

DEV-8417 OA3 update changes

---

sdk/tests/tutorials/ibor/test_valuation.py

scope is now required if storing recipe to lusid stores along with code.

DEV-8342 : addition of default scope to configuration recipe 

---

sdk/tests/tutorials/ibor/test_valuation.py

DEV-8335: Changing test to use new aggregation endpoint

---

sdk/lusid/utilities/api_client_builder.py
sdk/lusid/utilities/api_client_factory.py
sdk/tests/utilities/test_api_client_builder.py
sdk/tests/utilities/test_api_client_factory.py

This adds the ability to set correlation headers for api requests
ApiFactory tests were changed from ScopesApi.ListScopes to InstrumentsApi.GetInstrumentIndentifierTypes() because they are _much_ faster 😞

SE-292 Add correlation ids to requests

---

sdk/tests/tutorials/instruments/test_complex_instruments.py

Se 387.otc.examples.2

---

.github/workflows/main.yml

Update tests to run on commits directly to develop

---

sdk/tests/tutorials/ibor/test_reference_portfolios.py

Add test for F39: CreateReferencePortfolio

---

sdk/tests/tutorials/ibor/test_orders.py

Merge request to create a test to upsert a simple order

Feature/se 1016.upsert.simple.order.tutorial

---

sdk/lusid/__init__.py

This PR will add the ApiClientFactory to the module-level imports.

SE-1065: Add ApiClientFactory to module imports

---

sdk/tests/tutorials/valuation/test_valuation.py

DEV-10668 : migrate to valuation call

---

sdk/tests/tutorials/ibor/test_valuation.py
sdk/tests/tutorials/valuation/test_valuation.py

DEV-10668 : remove usages of aggregation call

---

sdk/tests/tutorials/instruments/test_complex_instruments.py

Feature/se 1119.add tests for term deposit

---

sdk/tests/tutorials/ibor/test_orders.py

- [ X ] Tests pass
- [ X ] Raised the PR against the `develop` branch
Upsert Prop def for props in Orders

PLAT-228: upsert prop def for each prop in Orders tests

---

.readthedocs.yaml
README.md
docs/Makefile
docs/README.md
docs/_static/pydata-custom.css
docs/_static/readthedocs-custom.css
docs/_templates/custom-class-template.rst
docs/_templates/custom-module-template.rst
docs/api.rst
docs/conf.py
docs/index.rst
docs/make.bat
docs/requirements.txt

SE-1192: Sphinx HTML doc setup for LUSID Python Preview SDK

---

sdk/tests/tutorials/marketdata/test_corporate_actions.py
sdk/tests/utilities/test_data_utilities.py

Add test for a name change corporate action

---

.github/workflows/build-and-test.yaml
.github/workflows/cron.yaml

SE-1381: add env var

---

.github/workflows/slack-on-pr.yaml

Gh actions

---

sdk/docker-compose.yml
sdk/lusid/utilities/api_client_builder.py
sdk/lusid/utilities/api_client_factory.py
sdk/lusid/utilities/api_configuration.py
sdk/lusid/utilities/api_configuration_loader.py
sdk/lusid/utilities/config_keys.json
sdk/tests/utilities/credentials_source.py
sdk/tests/utilities/test_api_client_builder.py
sdk/tests/utilities/test_api_client_factory.py
sdk/tests/utilities/test_api_client_factory_auth_flow.py

Feature/se 1381.add access token env var support

---

sdk/requirements.txt

Reverts finbourne/lusid-sdk-python-preview#136

Revert "add simplejson"

---

sdk/setup.py

Reverts finbourne/lusid-sdk-python-preview#137. revert setup.py update

Revert "Update setup.py"

---

sdk/tests/tutorials/ibor/test_reference_portfolios.py
sdk/tests/utilities/__init__.py
sdk/tests/utilities/id_generator.py
sdk/tests/utilities/test_id_generator.py

fix for https://github.com/finbourne/lusid-sdk-python-preview/pull/135

Seng 50.test.ids

---

sdk/tests/tutorials/ibor/test_bitemporal.py
sdk/tests/tutorials/ibor/test_cut_labels.py
sdk/tests/tutorials/ibor/test_holdings.py
sdk/tests/tutorials/ibor/test_orders.py
sdk/tests/tutorials/ibor/test_portfolios.py
sdk/tests/tutorials/ibor/test_properties.py
sdk/tests/tutorials/ibor/test_reconciliation.py
sdk/tests/tutorials/ibor/test_reference_portfolios.py
sdk/tests/tutorials/ibor/test_transactions.py
sdk/tests/tutorials/ibor/test_valuation.py
sdk/tests/tutorials/marketdata/test_corporate_actions.py
sdk/tests/tutorials/properties/test_derived_properties.py
sdk/tests/tutorials/properties/test_multivalue_properties.py
sdk/tests/tutorials/properties/test_transaction_properties.py
sdk/tests/utilities/id_generator.py
sdk/tests/utilities/id_generator_utilities.py
sdk/tests/utilities/test_id_generator.py

Delete created test entities on test completion

Seng 406.test.ids

---

sdk/tests/tutorials/ibor/test_portfolios.py

CTECH-760 Renamed portfolio feature

---

sdk/Dockerfile
sdk/docker-compose.yml
sdk/lusid/utilities/api_client_builder.py
sdk/lusid/utilities/api_client_factory.py
sdk/lusid/utilities/api_configuration.py
sdk/lusid/utilities/api_configuration_loader.py
sdk/lusid/utilities/config_keys.json
sdk/tests/utilities/credentials_source.py
sdk/tests/utilities/test_api_client_builder.py
sdk/tests/utilities/test_api_client_factory.py
sdk/tests/utilities/test_api_client_factory_auth_flow.py

SE-1381: add pat support

---

sdk/tests/tutorials/ibor/test_bitemporal.py
sdk/tests/tutorials/ibor/test_cut_labels.py
sdk/tests/tutorials/ibor/test_holdings.py
sdk/tests/tutorials/ibor/test_orders.py
sdk/tests/tutorials/ibor/test_portfolios.py
sdk/tests/tutorials/ibor/test_properties.py
sdk/tests/tutorials/ibor/test_reconciliation.py
sdk/tests/tutorials/ibor/test_reference_portfolios.py
sdk/tests/tutorials/ibor/test_transactions.py
sdk/tests/tutorials/ibor/test_valuation.py
sdk/tests/tutorials/marketdata/test_corporate_actions.py
sdk/tests/tutorials/marketdata/test_instruments.py
sdk/tests/tutorials/marketdata/test_quotes.py

- Migrated legacy labels of features in the python preview sdk to labels that reflect logical groupings e.g portfolios, instruments etc.

Ctech 409.migrate python preview

---

sdk/lusid/utilities/api_configuration_loader.py
sdk/tests/utilities/test_api_client_factory_auth_flow.py
sdk/tests/utilities/test_api_configuration_loader.py

change the log level to DEBUG when secrets files not found

CTECH-874 change missing secrets log level

---

sdk/tests/tutorials/ibor/test_cut_labels.py

CTECH-1096 handle duplicate cut labels

---

sdk/lusid/utilities/lusid_retry.py
sdk/tests/utilities/test_retry.py

Handle retry-after header when str

CTECH-1098 fix retry header when str

---

README.md

CTECH-1319 fixed typo in readme

---

sdk/setup.py

update setup.py versions for `requests` and `urllib3`

CTECH-1368 update setup.py versions

---

sdk/tests/tutorials/ibor/test_cut_labels.py

Fix cut label test to handle duplicates

CTECH-1096 fix cut label example

---

sdk/Dockerfile
sdk/lusid/utilities/api_client_builder.py
sdk/tests/tutorials/ibor/test_bitemporal.py
sdk/tests/tutorials/ibor/test_properties.py
sdk/tests/tutorials/marketdata/test_corporate_actions.py
sdk/tests/tutorials/properties/test_derived_properties.py
sdk/tests/utilities/credentials_source.py
sdk/tests/utilities/test_api_client_builder.py
sdk/tests/utilities/test_api_client_factory.py
sdk/tests/utilities/test_api_client_factory_auth_flow.py
sdk/tests/utilities/test_api_configuration_loader.py
sdk/tests/utilities/test_data_utilities.py
sdk/tests/utilities/test_retry.py
sdk/tests/utilities/test_token_refresh.py

Signed-off-by: Paul Saunders <pms1969@gmail.com>
Ensures that the forked PR flow can execute and pass tests that it is able to run.
This has required:
* Skipping tests that rely on a secrets.json file
* Some minor changes to some tests to use the PersonalAccessToken where appropriate.

CTECH-1344: Fix tests for forked PR flow.

---

sdk/requirements.txt
sdk/setup.py

Signed-off-by: Paul Saunders <paul.saunders@finbourne.com>
Unifies dependency versions with other LUSID platform SDK's.

CTECH-1723: Unifies dependency versions with other sdks.

---

sdk/setup.py

Remove incorrect version of setuputils and dependency

CTECH-1753 fix setup dependencies

---

sdk/setup.py

Adds minimum requirement for python version

CTECH-940: Adding minimum required python version
